# Generated by Django 5.1.5 on 2025-02-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_busca_cnpjs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesquisacnpj',
            name='api_key',
            field=models.CharField(default='default_api_key_padrão', max_length=270),
        ),
    ]
