# Generated by Django 5.1.5 on 2025-02-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_busca_cnpjs', '0002_pesquisacnpj_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesquisacnpj',
            name='api_key',
            field=models.CharField(max_length=270),
        ),
        migrations.AlterField(
            model_name='pesquisacnpj',
            name='cnpj',
            field=models.CharField(max_length=14),
        ),
    ]
