# Generated by Django 5.1.5 on 2025-02-05 18:43

import app_busca_cnpjs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_busca_cnpjs', '0003_alter_pesquisacnpj_api_key_alter_pesquisacnpj_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesquisacnpj',
            name='cnpj',
            field=models.CharField(max_length=14, validators=[app_busca_cnpjs.models.validate_cnpj]),
        ),
    ]
