# Generated by Django 5.1.5 on 2025-02-14 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_busca_cnpjs', '0005_buscaavancada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buscaavancada',
            old_name='estado',
            new_name='uf',
        ),
    ]
